return {
  "nvim-treesitter/nvim-treesitter",
  ---@type TSConfig
  opts = {
    ensure_installed = {
      "bash",
      "bibtex",
      "c",
      "cmake",
      "comment",
      "cpp",
      "css",
      "diff",
      "dockerfile",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "go",
      "gomod",
      "gosum",
      "gowork",
      "help",
      "html",
      "javascript",
      "json",
      "latex",
      "lua",
      "make",
      "markdown",
      "markdown_inline",
      "meson",
      "ninja",
      "nix",
      "proto",
      "python",
      "rust",
      "terraform",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "yaml",
      "query",
      "regex",
    },
  },
}
