{
  imports = [
    ./alacritty.nix
    ./aliases.nix
    ./bash.nix
    ./bat.nix
    ./cloud.nix
    ./dircolors.nix
    ./direnv.nix
    ./eza.nix
    ./fish.nix
    ./fzf.nix
    ./git.nix
    ./k9s.nix
    ./kubectl.nix
    ./lazydocker.nix
    ./lazygit.nix
    ./packages.nix
    ./packer.nix
    ./scripts.nix
    ./starship.nix
    ./systemd.nix
    ./terraform.nix
    ./tmux.nix
    ./todoist.nix
    ./vagrant.nix
    ./zoxide.nix
  ];
}
